# Render.com Docker deployment uchun sozlamalar
databases:
  - name: mysite-db
    databaseName: mysite
    user: mysite
    plan: free

services:
  - type: web
    name: kutubxona-online
    runtime: docker
    dockerfilePath: ./Dockerfile
    customDomains:
      - cloudstore.uz
      - www.cloudstore.uz
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,cloudstore.uz,www.cloudstore.uz"
      - key: DATABASE_URL
        fromDatabase:
          name: mysite-db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false
      - key: CLOUDCONVERT_API_KEY
        sync: false
    disk:
      name: media-storage
      mountPath: /app/media
      sizeGB: 1
